# Tukano App Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tukano-service
  labels:
    app: tukano-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tukano-service
  template:
    metadata:
      name: tukano-service
      labels:
        app: tukano-service
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: tukano-service
          image: joaosilva0102/tukano-users-shorts
          ports:
            - containerPort: 8080
      restartPolicy: Always
---
# Tukano App Service
apiVersion: v1
kind: Service
metadata:
  name: tukano-service
spec:
  selector:
    app: tukano-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer