# Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blobs-pvc
  namespace: tukano
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi