# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis-service
  ports:
    - name: http
      port: 6379
      targetPort: 6379
  type: ClusterIP
