# Redis Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-service
  labels:
    app: redis-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-service
  template:
    metadata:
      name: redis-service
      labels:
        app: redis-service
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: redis-service
          image: redis:latest
          ports:
            - containerPort: 6379
      restartPolicy: Always