# Blobs Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tukano-blobs-service
  namespace: tukano
  labels:
    app: tukano-blobs-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tukano-blobs-service
  template:
    metadata:
      name: tukano-blobs-service
      labels:
        app: tukano-blobs-service
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      volumes:
        - name: blobs-pv-storage
          persistentVolumeClaim:
            claimName: blobs-pvc
      containers:
        - name: tukano-blobs-service
          image: joaosilva0102/tukano-blobs
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/mnt/vol"
              name: blobs-pv-storage
      restartPolicy: Always