
apiVersion: v1
kind: Service
metadata:
  name: tukano-blobs-service
  namespace: tukano
spec:
  selector:
    app: tukano-blobs-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP