
---
# Tukano App Service
apiVersion: v1
kind: Service
metadata:
  name: tukano-users-shorts-service
  namespace: tukano
spec:
  selector:
    app: tukano-users-shorts-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP