# Blobs Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blob-service
  labels:
    app: blob-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blob-service
  template:
    metadata:
      name: blob-service
      labels:
        app: blob-service
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: blob-service
          image: joaosilva0102/tukano-blobs
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/mnt/vol"
              name: mediavolume
      volumes:
        - name: mediavolume
          persistentVolumeClaim:
            claimName: local-storage
      restartPolicy: Always